// <auto-generated />
namespace OnlineFoodOrdering.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _1to1Rel_Cust_Address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1to1Rel_Cust_Address));
        
        string IMigrationMetadata.Id
        {
            get { return "202205051051549_1to1Rel_Cust_Address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
